apiVersion: batch/v1
kind: Job
metadata:
  name: alpine-sleepgit1
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: alpine1
        image: alpine:latest
        command: ["/bin/sh", "-c", "sleep 6"]
      restartPolicy: Never
