apiVersion: batch/v1
kind: Job
metadata:
  name: {{job_yaml_file_params:jobname}}
spec:
  suspend: true
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: alpine1
        image: alpine:latest
        command: ["/bin/sh", "-c", "sleep {{job_yaml_file_params:tempo}} && echo Bonjour"]
      restartPolicy: Never
